[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
version = "2025.7.1-001"
name = "dps-common"
dependencies = []
requires-python = ">= 3.8"
authors = [
  {name = "Dan Short", email = "dshort@cossmn.cossmn"}
]
maintainers = [
  {name = "Dan Short", email = "dshort@cossmn.cossmn"}
]
description = "Common function Library"
readme = "README.md"
license = "GPL-3.0-or-later"